### ISSUE TITLE
warnings al ejecutar el proyecto (recién instalado)

### ISSUE THREAD

**Issue by serman** [politicalwatch/escaner2030.es#1]
Hola!
Aquí vengo a dar la brasa otra vez.

He instalado el proyecto
He creado un archivo .env.local con la url local y todo eso
```
BASE_URL=http://localhost:5174/
VITE_VUE_APP_SHORTNAME=escaner2030.es
VITE_VUE_APP_BACKEND_URL=https://api.quehacenlosdiputados.es
VITE_VUE_APP_USE_ALERTS=true
VUE_APP_SENTRY_DSN=
VITE_KNOWLEDGEBASE=ods
VITE_DEFAULT_LOCALE=es
VITE_FALLBACK_LOCALE=es
VITE_VUE_APP_TITLE='Escáner2030 - Escanea cualquier texto en clave ODS'
VITE_GA_ID=G-ZSVLWSY6F0
```

En footer-block he quitado el componente vue-cookie-accept-decline porque me daba error diciendo que no encuentra bootstrap.
Pero para mis pruebas no me hace falta.
( este error tambien me salta en produccion, solo para que lo sepais) 
![image](https://github.com/politicalwatch/escaner2030.es/assets/320123/f14c8129-9faf-4096-81b9-106620c4b9b9)

---- 
Ahora **el asunto por el que os pregunto** es que al abrir una iniciativa me da un montón de warnings el componente scanner-table
http://localhost:5174/scanner/c4db99a487b0b9bcfb23892e88af539afce9f101

![image](https://github.com/politicalwatch/escaner2030.es/assets/320123/2aaab0b5-d132-4bd1-8db7-066441cc9f47)
No se si me interferirá para lo que voy a hacer, pero quiero ver si es que es algo de que tengo el proyecto mal configurado ¿Tengo que editar algo mas para funcionar bien? 

Gracias por anticipado

**Comment by alex-ahumada** [comment]
¡Gracias por el aviso! No creo que afectase a tus tareas pero lo hemos arreglado en https://github.com/politicalwatch/escaner2030.es/commit/e654f69ca7bceda34a2f02551275f7fe1e359245

En cuanto al problema con **vue-cookie-accept-decline,** no he podido reproducir el error. Cierro la issue por ahora y si te da más problemas me lo comentas y abrimos otra.
